version: "3"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: nanbe-postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nanbe
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nanbe-redis
    ports:
      - '6370:6379'
    command: redis-server --appendonly yes --notify-keyspace-events Ex
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local