export const EMOJI_GROUPS = [
    {
        name: "Smileys & People",
        emojis: [
            { c: "😀", n: "grinning" },
            { c: "😃", n: "smiley" },
            { c: "😄", n: "smile" },
            { c: "😁", n: "grin" },
            { c: "😆", n: "laughing" },
            { c: "😅", n: "sweat_smile" },
            { c: "🤣", n: "rofl" },
            { c: "😂", n: "joy" },
            { c: "🙂", n: "slightly_smiling_face" },
            { c: "🙃", n: "upside_down_face" },
            { c: "😉", n: "wink" },
            { c: "😊", n: "blush" },
            { c: "😇", n: "innocent" },
            { c: "🥰", n: "smiling_face_with_hearts" },
            { c: "😍", n: "heart_eyes" },
            { c: "🤩", n: "star_struck" },
            { c: "😘", n: "kissing_heart" },
            { c: "😗", n: "kissing" },
            { c: "😚", n: "kissing_closed_eyes" },
            { c: "😙", n: "kissing_smiling_eyes" },
            { c: "😋", n: "yum" },
            { c: "😛", n: "stuck_out_tongue" },
            { c: "😜", n: "stuck_out_tongue_winking_eye" },
            { c: "🤪", n: "zany_face" },
            { c: "😝", n: "stuck_out_tongue_closed_eyes" },
            { c: "🤑", n: "money_mouth_face" },
            { c: "🤗", n: "hugs" },
            { c: "🤭", n: "hand_over_mouth" },
            { c: "🤫", n: "shushing_face" },
            { c: "🤔", n: "thinking" },
            { c: "🤐", n: "zipper_mouth_face" },
            { c: "🤨", n: "raised_eyebrow" },
            { c: "😐", n: "neutral_face" },
            { c: "😑", n: "expressionless" },
            { c: "😶", n: "no_mouth" },
            { c: "😏", n: "smirk" },
            { c: "😒", n: "unamused" },
            { c: "🙄", n: "roll_eyes" },
            { c: "😬", n: "grimacing" },
            { c: "😌", n: "relieved" },
            { c: "😔", n: "pensive" },
            { c: "😪", n: "sleepy" },
            { c: "🤤", n: "drooling_face" },
            { c: "😴", n: "sleeping" },
            { c: "😷", n: "mask" },
            { c: "🤒", n: "face_with_thermometer" },
            { c: "🤕", n: "face_with_head_bandage" },
            { c: "🤢", n: "nauseated_face" },
            { c: "🤮", n: "vomiting_face" },
            { c: "🤧", n: "sneezing_face" },
            { c: "🥵", n: "hot_face" },
            { c: "🥶", n: "cold_face" },
            { c: "😵", n: "dizzy_face" },
            { c: "🤯", n: "exploding_head" },
            { c: "🤠", n: "cowboy_hat_face" },
            { c: "🥳", n: "partying_face" },
            { c: "😎", n: "sunglasses" },
            { c: "🤓", n: "nerd_face" },
            { c: "🧐", n: "monocle_face" },
            { c: "😕", n: "confused" },
            { c: "😟", n: "worried" },
            { c: "🙁", n: "slightly_frowning_face" },
            { c: "😮", n: "open_mouth" },
            { c: "😯", n: "hushed" },
            { c: "😲", n: "astonished" },
            { c: "😳", n: "flushed" },
            { c: "🥺", n: "pleading_face" },
            { c: "😦", n: "frowning" },
            { c: "😨", n: "fearful" },
            { c: "😰", n: "anxious_face_with_sweat" },
            { c: "😥", n: "sad_but_relieved_face" },
            { c: "😢", n: "cry" },
            { c: "😭", n: "sob" },
            { c: "😱", n: "scream" },
            { c: "😖", n: "confounded" },
            { c: "😣", n: "persevere" },
            { c: "😞", n: "disappointed" },
            { c: "😓", n: "downcast_face_with_sweat" },
            { c: "😩", n: "weary" },
            { c: "😫", n: "tired_face" },
            { c: "🥱", n: "yawning_face" },
            { c: "😤", n: "triumph" },
            { c: "😡", n: "rage" },
            { c: "😠", n: "angry" },
            { c: "🤬", n: "cursing_face" },
            { c: "😈", n: "smiling_imp" },
            { c: "👿", n: "imp" },
            { c: "💀", n: "skull" },
            { c: "☠️", n: "skull_and_crossbones" },
            { c: "💩", n: "poop" },
            { c: "🤡", n: "clown_face" },
            { c: "👹", n: "japanese_ogre" },
            { c: "👻", n: "ghost" },
            { c: "👽", n: "alien" },
            { c: "🤖", n: "robot" },
            { c: "🙏", n: "pray" },
            { c: "👋", n: "wave" },
            { c: "🙌", n: "raised_hands" },
            { c: "👏", n: "clap" },
            { c: "👍", n: "thumbsup" },
            { c: "👎", n: "thumbsdown" },
            { c: "🤝", n: "handshake" },
            { c: "💪", n: "muscle" },
            { c: "🫶", n: "heart_hands" },
            { c: "🤷", n: "shrug" },
            { c: "🤦", n: "facepalm" },
            { c: "👀", n: "eyes" },
        ],
    },
    {
        name: "Animals & Nature",
        emojis: [
            { c: "🐶", n: "dog" },
            { c: "🐱", n: "cat" },
            { c: "🐭", n: "mouse" },
            { c: "🐹", n: "hamster" },
            { c: "🐰", n: "rabbit" },
            { c: "🦊", n: "fox" },
            { c: "🐻", n: "bear" },
            { c: "🐼", n: "panda" },
            { c: "🐨", n: "koala" },
            { c: "🐯", n: "tiger" },
            { c: "🦁", n: "lion" },
            { c: "🐮", n: "cow" },
            { c: "🐷", n: "pig" },
            { c: "🐵", n: "monkey_face" },
            { c: "🐸", n: "frog" },
            { c: "🐔", n: "chicken" },
            { c: "🐧", n: "penguin" },
            { c: "🐦", n: "bird" },
            { c: "🦄", n: "unicorn" },
            { c: "🐝", n: "bee" },
            { c: "🦋", n: "butterfly" },
            { c: "🐢", n: "turtle" },
            { c: "🐙", n: "octopus" },
            { c: "🐳", n: "whale" },
            { c: "🐬", n: "dolphin" },
            { c: "🐟", n: "fish" },
            { c: "🦈", n: "shark" },
            { c: "🌵", n: "cactus" },
            { c: "🌲", n: "evergreen_tree" },
            { c: "🌴", n: "palm_tree" },
            { c: "🍀", n: "four_leaf_clover" },
            { c: "🍁", n: "maple_leaf" },
            { c: "🌸", n: "cherry_blossom" },
            { c: "🌻", n: "sunflower" },
            { c: "🌹", n: "rose" },
            { c: "🌈", n: "rainbow" },
            { c: "⭐", n: "star" },
            { c: "🌟", n: "star2" },
            { c: "✨", n: "sparkles" },
            { c: "⚡", n: "zap" },
            { c: "🔥", n: "fire" },
            { c: "💧", n: "droplet" },
            { c: "🌊", n: "ocean" },
            { c: "☀️", n: "sunny" },
            { c: "🌙", n: "crescent_moon" },
            { c: "☁️", n: "cloud" },
            { c: "❄️", n: "snowflake" },
        ],
    },
    {
        name: "Food & Drink",
        emojis: [
            { c: "🍎", n: "apple" },
            { c: "🍌", n: "banana" },
            { c: "🍇", n: "grapes" },
            { c: "🍓", n: "strawberry" },
            { c: "🍑", n: "peach" },
            { c: "🍍", n: "pineapple" },
            { c: "🥑", n: "avocado" },
            { c: "🍅", n: "tomato" },
            { c: "🥕", n: "carrot" },
            { c: "🌽", n: "corn" },
            { c: "🥐", n: "croissant" },
            { c: "🍞", n: "bread" },
            { c: "🧀", n: "cheese" },
            { c: "🍔", n: "hamburger" },
            { c: "🍟", n: "fries" },
            { c: "🍕", n: "pizza" },
            { c: "🌮", n: "taco" },
            { c: "🌯", n: "burrito" },
            { c: "🍜", n: "ramen" },
            { c: "🍣", n: "sushi" },
            { c: "🍤", n: "fried_shrimp" },
            { c: "🍙", n: "rice_ball" },
            { c: "🥗", n: "green_salad" },
            { c: "🍰", n: "cake" },
            { c: "🎂", n: "birthday" },
            { c: "🍪", n: "cookie" },
            { c: "🍩", n: "doughnut" },
            { c: "🍫", n: "chocolate_bar" },
            { c: "🍿", n: "popcorn" },
            { c: "🍦", n: "icecream" },
            { c: "☕", n: "coffee" },
            { c: "🍵", n: "tea" },
            { c: "🍺", n: "beer" },
            { c: "🍷", n: "wine_glass" },
            { c: "🍸", n: "cocktail" },
            { c: "🥂", n: "clinking_glasses" },
            { c: "🍾", n: "champagne" },
        ],
    },
    {
        name: "Activity",
        emojis: [
            { c: "⚽", n: "soccer" },
            { c: "🏀", n: "basketball" },
            { c: "🏈", n: "football" },
            { c: "⚾", n: "baseball" },
            { c: "🎾", n: "tennis" },
            { c: "🏐", n: "volleyball" },
            { c: "🏓", n: "ping_pong" },
            { c: "🏸", n: "badminton" },
            { c: "🥊", n: "boxing_glove" },
            { c: "🏋️", n: "weight_lifting" },
            { c: "🚴", n: "bicyclist" },
            { c: "🏃", n: "runner" },
            { c: "🏊", n: "swimmer" },
            { c: "🧗", n: "climbing" },
            { c: "🏆", n: "trophy" },
            { c: "🥇", n: "1st_place_medal" },
            { c: "🎯", n: "dart" },
            { c: "🎲", n: "game_die" },
            { c: "🎮", n: "video_game" },
            { c: "🎰", n: "slot_machine" },
            { c: "🎨", n: "art" },
            { c: "🎭", n: "performing_arts" },
            { c: "🎤", n: "microphone" },
            { c: "🎧", n: "headphones" },
            { c: "🎸", n: "guitar" },
            { c: "🥁", n: "drum" },
            { c: "🎹", n: "musical_keyboard" },
            { c: "🎬", n: "clapper" },
            { c: "🎉", n: "tada" },
            { c: "🎊", n: "confetti_ball" },
            { c: "🎈", n: "balloon" },
            { c: "🎁", n: "gift" },
        ],
    },
    {
        name: "Travel & Places",
        emojis: [
            { c: "🚗", n: "car" },
            { c: "🚕", n: "taxi" },
            { c: "🚌", n: "bus" },
            { c: "🚑", n: "ambulance" },
            { c: "🚓", n: "police_car" },
            { c: "🏎️", n: "racing_car" },
            { c: "🏍️", n: "motorcycle" },
            { c: "🚲", n: "bike" },
            { c: "🛴", n: "kick_scooter" },
            { c: "🚂", n: "steam_locomotive" },
            { c: "🚆", n: "train" },
            { c: "🚇", n: "metro" },
            { c: "✈️", n: "airplane" },
            { c: "🚀", n: "rocket" },
            { c: "🛸", n: "flying_saucer" },
            { c: "🚁", n: "helicopter" },
            { c: "⛵", n: "sailboat" },
            { c: "🚢", n: "ship" },
            { c: "⚓", n: "anchor" },
            { c: "🗺️", n: "world_map" },
            { c: "🗽", n: "statue_of_liberty" },
            { c: "🗼", n: "tokyo_tower" },
            { c: "🏰", n: "european_castle" },
            { c: "🏝️", n: "desert_island" },
            { c: "🏔️", n: "mountain_snow" },
            { c: "🌋", n: "volcano" },
            { c: "🏕️", n: "camping" },
            { c: "🏠", n: "house" },
            { c: "🏢", n: "office" },
            { c: "🏥", n: "hospital" },
            { c: "🏦", n: "bank" },
            { c: "🌍", n: "earth_africa" },
            { c: "🌎", n: "earth_americas" },
            { c: "🌏", n: "earth_asia" },
        ],
    },
    {
        name: "Objects",
        emojis: [
            { c: "💻", n: "computer" },
            { c: "🖥️", n: "desktop_computer" },
            { c: "⌨️", n: "keyboard" },
            { c: "🖱️", n: "computer_mouse" },
            { c: "🖨️", n: "printer" },
            { c: "📱", n: "iphone" },
            { c: "📷", n: "camera" },
            { c: "📹", n: "video_camera" },
            { c: "🔋", n: "battery" },
            { c: "🔌", n: "electric_plug" },
            { c: "💡", n: "bulb" },
            { c: "🔦", n: "flashlight" },
            { c: "🔍", n: "mag" },
            { c: "🔒", n: "lock" },
            { c: "🔑", n: "key" },
            { c: "🔨", n: "hammer" },
            { c: "🪛", n: "screwdriver" },
            { c: "🔧", n: "wrench" },
            { c: "⚙️", n: "gear" },
            { c: "🧲", n: "magnet" },
            { c: "🧪", n: "test_tube" },
            { c: "🔬", n: "microscope" },
            { c: "🔭", n: "telescope" },
            { c: "📡", n: "satellite" },
            { c: "💰", n: "moneybag" },
            { c: "💳", n: "credit_card" },
            { c: "💎", n: "gem" },
            { c: "📦", n: "package" },
            { c: "📬", n: "mailbox" },
            { c: "✏️", n: "pencil" },
            { c: "📝", n: "memo" },
            { c: "📌", n: "pushpin" },
            { c: "📎", n: "paperclip" },
            { c: "📅", n: "date" },
            { c: "📊", n: "bar_chart" },
            { c: "📈", n: "chart_increasing" },
            { c: "📚", n: "books" },
            { c: "🗑️", n: "wastebasket" },
        ],
    },
    {
        name: "Symbols",
        emojis: [
            { c: "❤️", n: "heart" },
            { c: "🧡", n: "orange_heart" },
            { c: "💛", n: "yellow_heart" },
            { c: "💚", n: "green_heart" },
            { c: "💙", n: "blue_heart" },
            { c: "💜", n: "purple_heart" },
            { c: "🖤", n: "black_heart" },
            { c: "💔", n: "broken_heart" },
            { c: "💯", n: "100" },
            { c: "✅", n: "white_check_mark" },
            { c: "☑️", n: "ballot_box_with_check" },
            { c: "❌", n: "x" },
            { c: "⚠️", n: "warning" },
            { c: "🚫", n: "no_entry_sign" },
            { c: "❓", n: "question" },
            { c: "❗", n: "exclamation" },
            { c: "💤", n: "zzz" },
            { c: "💥", n: "boom" },
            { c: "💫", n: "dizzy" },
            { c: "🔔", n: "bell" },
            { c: "🔕", n: "no_bell" },
            { c: "🔗", n: "link" },
            { c: "♻️", n: "recycle" },
            { c: "🔄", n: "arrows_counterclockwise" },
            { c: "▶️", n: "arrow_forward" },
            { c: "⏸️", n: "pause_button" },
            { c: "⏹️", n: "stop_button" },
            { c: "🔺", n: "small_red_triangle" },
            { c: "🔻", n: "small_red_triangle_down" },
            { c: "🟢", n: "green_circle" },
            { c: "🟡", n: "yellow_circle" },
            { c: "🔴", n: "red_circle" },
            { c: "🔵", n: "blue_circle" },
            { c: "⚫", n: "black_circle" },
            { c: "⚪", n: "white_circle" },
            { c: "🏁", n: "checkered_flag" },
            { c: "🚩", n: "triangular_flag" },
        ],
    },
];
