import {
    PiAirplaneFill,
    PiAlarmFill,
    PiAnchorFill,
    PiArchiveFill,
    PiAtomFill,
    PiBalloonFill,
    PiBandaidsFill,
    PiBarbellFill,
    PiBaseballFill,
    PiBasketballFill,
    PiBatteryFullFill,
    PiBedFill,
    PiBellFill,
    PiBicycleFill,
    PiBinocularsFill,
    PiBirdFill,
    PiBoatFill,
    PiBookFill,
    PiBookmarkFill,
    PiBookOpenFill,
    PiBowlFoodFill,
    PiBriefcaseFill,
    PiBugFill,
    PiBusFill,
    PiButterflyFill,
    PiCakeFill,
    PiCalculatorFill,
    PiCalendarFill,
    PiCameraFill,
    PiCardsFill,
    PiCarFill,
    PiCassetteTapeFill,
    PiCastleTurretFill,
    PiCatFill,
    PiChampagneFill,
    PiChartBarFill,
    PiChatCircleFill,
    PiCheckCircleFill,
    PiCirclesThreeFill,
    PiCircuitryFill,
    PiClipboardFill,
    PiClockFill,
    PiCloudArrowUpFill,
    PiCloudFill,
    PiCloudLightningFill,
    PiCoatHangerFill,
    PiCodeFill,
    PiCoffeeFill,
    PiCompassFill,
    PiConfettiFill,
    PiCookieFill,
    PiCowFill,
    PiCpuFill,
    PiCraneTowerFill,
    PiCreditCardFill,
    PiCrosshairFill,
    PiCrownFill,
    PiCubeFill,
    PiCurrencyDollarFill,
    PiDatabaseFill,
    PiDesktopFill,
    PiDeviceMobileFill,
    PiDiamondFill,
    PiDiceFiveFill,
    PiDnaFill,
    PiDogFill,
    PiDropFill,
    PiEarFill,
    PiEnvelopeFill,
    PiEraserFill,
    PiEyeFill,
    PiFeatherFill,
    PiFileFill,
    PiFilmSlateFill,
    PiFireExtinguisherFill,
    PiFireFill,
    PiFirstAidFill,
    PiFishFill,
    PiFlagFill,
    PiFlashlightFill,
    PiFlaskFill,
    PiFloppyDiskFill,
    PiFlowerFill,
    PiFolderFill,
    PiFootballFill,
    PiGameControllerFill,
    PiGarageFill,
    PiGearFill,
    PiGiftFill,
    PiGitBranchFill,
    PiGlobeFill,
    PiGlobeHemisphereEastFill,
    PiGlobeHemisphereWestFill,
    PiGlobeStandFill,
    PiGolfFill,
    PiGraduationCapFill,
    PiHamburgerFill,
    PiHammerFill,
    PiHandbagFill,
    PiHandFill,
    PiHardDrivesFill,
    PiHeadphonesFill,
    PiHeartFill,
    PiHorseFill,
    PiHourglassFill,
    PiInfoFill,
    PiKeyboardFill,
    PiKeyFill,
    PiLaptopFill,
    PiLeafFill,
    PiLightbulbFill,
    PiLightningFill,
    PiLockFill,
    PiMagicWandFill,
    PiMapPinFill,
    PiMapTrifoldFill,
    PiMaskHappyFill,
    PiMedalFill,
    PiMegaphoneFill,
    PiMicrophoneFill,
    PiMinusCircleFill,
    PiMoonFill,
    PiMotorcycleFill,
    PiMountainsFill,
    PiMouseFill,
    PiMusicNotesFill,
    PiNotepadFill,
    PiPackageFill,
    PiPaintBrushFill,
    PiPaintBucketFill,
    PiPaintRollerFill,
    PiPaperPlaneTiltFill,
    PiPawPrintFill,
    PiPersonFill,
    PiPersonSimpleRunFill,
    PiPersonSimpleWalkFill,
    PiPhoneFill,
    PiPiggyBankFill,
    PiPillFill,
    PiPingPongFill,
    PiPizzaFill,
    PiPlanetFill,
    PiPlugFill,
    PiPlusCircleFill,
    PiPowerFill,
    PiPrinterFill,
    PiPulseFill,
    PiPuzzlePieceFill,
    PiQuestionFill,
    PiRabbitFill,
    PiRadioFill,
    PiRecycleFill,
    PiRocketFill,
    PiRulerFill,
    PiSailboatFill,
    PiScissorsFill,
    PiShieldCheckFill,
    PiShoppingCartFill,
    PiShrimpFill,
    PiSkullFill,
    PiSmileyBlankFill,
    PiSmileyFill,
    PiSmileyNervousFill,
    PiSmileySadFill,
    PiSmileyStickerFill,
    PiSmileyWinkFill,
    PiSmileyXEyesFill,
    PiSnowflakeFill,
    PiSoccerBallFill,
    PiSparkleFill,
    PiSpeakerHighFill,
    PiSquaresFourFill,
    PiStackFill,
    PiStarFill,
    PiStorefrontFill,
    PiSunFill,
    PiTagFill,
    PiTaxiFill,
    PiTelevisionFill,
    PiTennisBallFill,
    PiTerminalFill,
    PiThumbsDownFill,
    PiThumbsUpFill,
    PiTicketFill,
    PiTimerFill,
    PiToolboxFill,
    PiTrafficConeFill,
    PiTrainFill,
    PiTramFill,
    PiTrashFill,
    PiTreeFill,
    PiTrophyFill,
    PiTShirtFill,
    PiUmbrellaFill,
    PiUserCircleFill,
    PiUserFill,
    PiUsersFill,
    PiVanFill,
    PiVideoCameraFill,
    PiVolleyballFill,
    PiWalletFill,
    PiWallFill,
    PiWarningFill,
    PiWheelchairFill,
    PiWifiHighFill,
    PiWrenchFill,
    PiXCircleFill,
} from "react-icons/pi";

export const ICONS = {
    stack: PiStackFill,
    smiley: PiSmileyFill,
    "smiley-sad": PiSmileySadFill,
    "smiley-blank": PiSmileyBlankFill,
    "smiley-wink": PiSmileyWinkFill,
    "smiley-x-eyes": PiSmileyXEyesFill,
    "smiley-nervous": PiSmileyNervousFill,
    "smiley-sticker": PiSmileyStickerFill,
    user: PiUserFill,
    users: PiUsersFill,
    "user-circle": PiUserCircleFill,
    "mask-happy": PiMaskHappyFill,
    person: PiPersonFill,
    wheelchair: PiWheelchairFill,
    dna: PiDnaFill,
    heart: PiHeartFill,
    "first-aid": PiFirstAidFill,
    bandaids: PiBandaidsFill,
    pill: PiPillFill,
    pulse: PiPulseFill,
    ear: PiEarFill,
    skull: PiSkullFill,
    "thumbs-up": PiThumbsUpFill,
    "thumbs-down": PiThumbsDownFill,
    leaf: PiLeafFill,
    tree: PiTreeFill,
    flower: PiFlowerFill,
    feather: PiFeatherFill,
    mountains: PiMountainsFill,
    star: PiStarFill,
    sun: PiSunFill,
    cloud: PiCloudFill,
    "cloud-lightning": PiCloudLightningFill,
    lightning: PiLightningFill,
    fire: PiFireFill,
    umbrella: PiUmbrellaFill,
    snowflake: PiSnowflakeFill,
    drop: PiDropFill,
    cat: PiCatFill,
    dog: PiDogFill,
    bird: PiBirdFill,
    fish: PiFishFill,
    butterfly: PiButterflyFill,
    horse: PiHorseFill,
    rabbit: PiRabbitFill,
    cow: PiCowFill,
    shrimp: PiShrimpFill,
    "paw-print": PiPawPrintFill,
    hamburger: PiHamburgerFill,
    coffee: PiCoffeeFill,
    cookie: PiCookieFill,
    pizza: PiPizzaFill,
    "bowl-food": PiBowlFoodFill,
    cake: PiCakeFill,
    champagne: PiChampagneFill,
    football: PiFootballFill,
    basketball: PiBasketballFill,
    "soccer-ball": PiSoccerBallFill,
    baseball: PiBaseballFill,
    "tennis-ball": PiTennisBallFill,
    volleyball: PiVolleyballFill,
    barbell: PiBarbellFill,
    golf: PiGolfFill,
    "ping-pong": PiPingPongFill,
    "person-simple-run": PiPersonSimpleRunFill,
    "person-simple-walk": PiPersonSimpleWalkFill,
    bicycle: PiBicycleFill,
    trophy: PiTrophyFill,
    medal: PiMedalFill,
    "dice-five": PiDiceFiveFill,
    cards: PiCardsFill,
    "puzzle-piece": PiPuzzlePieceFill,
    confetti: PiConfettiFill,
    balloon: PiBalloonFill,
    microphone: PiMicrophoneFill,
    "music-notes": PiMusicNotesFill,
    "cassette-tape": PiCassetteTapeFill,
    "speaker-high": PiSpeakerHighFill,
    headphones: PiHeadphonesFill,
    "game-controller": PiGameControllerFill,
    camera: PiCameraFill,
    "video-camera": PiVideoCameraFill,
    "film-slate": PiFilmSlateFill,
    television: PiTelevisionFill,
    radio: PiRadioFill,
    "traffic-cone": PiTrafficConeFill,
    cube: PiCubeFill,
    "paint-brush": PiPaintBrushFill,
    "paint-bucket": PiPaintBucketFill,
    "paint-roller": PiPaintRollerFill,
    handbag: PiHandbagFill,
    scissors: PiScissorsFill,
    eraser: PiEraserFill,
    ruler: PiRulerFill,
    "magic-wand": PiMagicWandFill,
    flashlight: PiFlashlightFill,
    gear: PiGearFill,
    lock: PiLockFill,
    binoculars: PiBinocularsFill,
    "fire-extinguisher": PiFireExtinguisherFill,
    toolbox: PiToolboxFill,
    wrench: PiWrenchFill,
    hammer: PiHammerFill,
    key: PiKeyFill,
    "crane-tower": PiCraneTowerFill,
    book: PiBookFill,
    "book-open": PiBookOpenFill,
    bookmark: PiBookmarkFill,
    briefcase: PiBriefcaseFill,
    calculator: PiCalculatorFill,
    notepad: PiNotepadFill,
    bed: PiBedFill,
    package: PiPackageFill,
    "coat-hanger": PiCoatHangerFill,
    "t-shirt": PiTShirtFill,
    wall: PiWallFill,
    garage: PiGarageFill,
    lightbulb: PiLightbulbFill,
    sparkle: PiSparkleFill,
    atom: PiAtomFill,
    gift: PiGiftFill,
    "shield-check": PiShieldCheckFill,
    crown: PiCrownFill,
    recycle: PiRecycleFill,
    hourglass: PiHourglassFill,
    megaphone: PiMegaphoneFill,
    flask: PiFlaskFill,
    diamond: PiDiamondFill,
    compass: PiCompassFill,
    "map-pin": PiMapPinFill,
    "map-trifold": PiMapTrifoldFill,
    airplane: PiAirplaneFill,
    rocket: PiRocketFill,
    boat: PiBoatFill,
    sailboat: PiSailboatFill,
    anchor: PiAnchorFill,
    car: PiCarFill,
    taxi: PiTaxiFill,
    bus: PiBusFill,
    train: PiTrainFill,
    tram: PiTramFill,
    van: PiVanFill,
    motorcycle: PiMotorcycleFill,
    globe: PiGlobeFill,
    "globe-hemisphere-west": PiGlobeHemisphereWestFill,
    "globe-hemisphere-east": PiGlobeHemisphereEastFill,
    "globe-stand": PiGlobeStandFill,
    planet: PiPlanetFill,
    moon: PiMoonFill,
    "castle-turret": PiCastleTurretFill,
    storefront: PiStorefrontFill,
    "graduation-cap": PiGraduationCapFill,
    laptop: PiLaptopFill,
    desktop: PiDesktopFill,
    "device-mobile": PiDeviceMobileFill,
    keyboard: PiKeyboardFill,
    mouse: PiMouseFill,
    printer: PiPrinterFill,
    "floppy-disk": PiFloppyDiskFill,
    "hard-drives": PiHardDrivesFill,
    database: PiDatabaseFill,
    cpu: PiCpuFill,
    circuitry: PiCircuitryFill,
    code: PiCodeFill,
    terminal: PiTerminalFill,
    bug: PiBugFill,
    "git-branch": PiGitBranchFill,
    "cloud-arrow-up": PiCloudArrowUpFill,
    "wifi-high": PiWifiHighFill,
    "battery-full": PiBatteryFullFill,
    plug: PiPlugFill,
    power: PiPowerFill,
    "check-circle": PiCheckCircleFill,
    "x-circle": PiXCircleFill,
    warning: PiWarningFill,
    info: PiInfoFill,
    question: PiQuestionFill,
    "plus-circle": PiPlusCircleFill,
    "minus-circle": PiMinusCircleFill,
    bell: PiBellFill,
    "chat-circle": PiChatCircleFill,
    envelope: PiEnvelopeFill,
    "paper-plane-tilt": PiPaperPlaneTiltFill,
    phone: PiPhoneFill,
    flag: PiFlagFill,
    tag: PiTagFill,
    eye: PiEyeFill,
    hand: PiHandFill,
    crosshair: PiCrosshairFill,
    "squares-four": PiSquaresFourFill,
    "circles-three": PiCirclesThreeFill,
    folder: PiFolderFill,
    file: PiFileFill,
    clipboard: PiClipboardFill,
    calendar: PiCalendarFill,
    clock: PiClockFill,
    alarm: PiAlarmFill,
    timer: PiTimerFill,
    ticket: PiTicketFill,
    "currency-dollar": PiCurrencyDollarFill,
    "credit-card": PiCreditCardFill,
    wallet: PiWalletFill,
    "piggy-bank": PiPiggyBankFill,
    "shopping-cart": PiShoppingCartFill,
    "chart-bar": PiChartBarFill,
    trash: PiTrashFill,
    archive: PiArchiveFill,
};
