const Action = {
    org: {
        read: "read",
        update: "update",
        delete: "delete",
        invite_member: "invite_member",
        remove_member: "remove_member",
        change_member_role: "change_member_role",
        manage_billing: "manage_billing",
        create_project: "create_project",
        manage_connectors: "manage_connectors",
        write_envs: "write_env_access",
        read_envs: "read_envs",
    },
    project: {
        read: "read",
        update: "update",
        delete: "delete",
        create_team: "create_team",
        manage_team: "manage_team",
        create_issue: "create_issue",
        triage_issue: "triage_issue",
        close_issue: "close_issue",
        assign_issue: "assign_issue",
        manage_columns: "manage_columns",
        manage_tags: "manage_tags",
        manage_templates: "manage_templates",
        trigger_runner: "trigger_runner",
        cancel_runner: "cancel_runner",
        view_runner_logs: "view_runner_logs",
        manage_connectors: "manage_connectors",
        write_envs: "write_env_access",
        read_envs: "read_envs",
    },
    team: {
        read: "read",
        update: "update",
        add_member: "add_member",
        remove_member: "remove_member",
        change_member_role: "change_member_role",
        write_envs: "write_env_access",
        read_envs: "read_envs",
    },
} as const;

export default Action;
